### ISSUE TITLE
findings matching query does not exist

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1253]
```
WARNING ------------Table: findings--------------
WARNING 
        ---------------------PROBLEM---------------------
        findings, data_distro/data_to_load/test_data/findings.txt
        ----
        {'Finding': {'dbkey': None, 'audit_year': 2013, 'audit_id': 14012297, 'audit_findings_id': 96, 'finding_ref_number': '2013-021', 'type_requirement': 'M', 'modified_opinion': False, 'other_non_compliance': True, 'material_weakness': False, 'significant_deficiency': True, 'other_findings': False, 'questioned_costs': False, 'repeat_finding': None, 'prior_finding_ref_numbers': None, 'is_public': True}}
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
data_distro.models.Finding.DoesNotExist: Finding matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/newrelic/hooks/database_psycopg2.py", line 64, in execute
    return super(CursorWrapper, self).execute(sql, parameters, *args,
  File "/usr/local/lib/python3.10/site-packages/newrelic/hooks/database_dbapi2.py", line 37, in execute
    return self.__wrapped__.execute(sql, parameters,
psycopg2.errors.NotNullViolation: null value in column "dbkey" violates not-null constraint
DETAIL:  Failing row contains (2, f, t, f, t, f, f, null, 2013-021, null, M, 14012297, 96, 2013, null, t).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/data_distro/management/commands/process_data.py", line 178, in transform_and_save
    objects_dict = create_objects_dict(instances_dict)
  File "/src/data_distro/management/commands/process_data.py", line 157, in create_objects_dict
    new_instance, _created = fac_model.objects.get_or_create(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 923, in get_or_create
    return self.create(**params), True
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/newrelic/hooks/database_psycopg2.py", line 64, in execute
    return super(CursorWrapper, self).execute(sql, parameters, *args,
  File "/usr/local/lib/python3.10/site-packages/newrelic/hooks/database_dbapi2.py", line 37, in execute
    return self.__wrapped__.execute(sql, parameters,
django.db.utils.IntegrityError: null value in column "dbkey" violates not-null constraint
DETAIL:  Failing row contains (2, f, t, f, t, f, f, null, 2013-021, null, M, 14012297, 96, 2013, null, t).

```

**Comment by jadudm** [comment]
Also

```
WARNING 
        ---------------------PROBLEM---------------------
        findings, data_distro/data_to_load/test_data/findings.txt
        ----
        {'Finding': {'dbkey': None, 'audit_year': 2013, 'audit_id': 14012304, 'audit_findings_id': 98, 'finding_ref_number': '2013-025', 'type_requirement': 'M', 'modified_opinion': False, 'other_non_compliance': True, 'material_weakness': False, 'significant_deficiency': True, 'other_findings': False, 'questioned_costs': False, 'repeat_finding': None, 'prior_finding_ref_numbers': None, 'is_public': True}}
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
data_distro.models.Finding.DoesNotExist: Finding matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/newrelic/hooks/database_psycopg2.py", line 64, in execute
    return super(CursorWrapper, self).execute(sql, parameters, *args,
  File "/usr/local/lib/python3.10/site-packages/newrelic/hooks/database_dbapi2.py", line 37, in execute
    return self.__wrapped__.execute(sql, parameters,
psycopg2.errors.NotNullViolation: null value in column "dbkey" violates not-null constraint
DETAIL:  Failing row contains (3, f, t, f, t, f, f, null, 2013-025, null, M, 14012304, 98, 2013, null, t).
```

which appears that there is one problem that repeats.
