### ISSUE TITLE
filename should be generated from fieldname

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1255]
```
On instance['CorrectiveActionPlan']['corrective_action_plan_entries'][0]:
    {'contains_chart_or_table': 'Y', 'reference_number': '2023-001'}
....................................................EEEE
======================================================================
ERROR: test_filename_generated (audit.test_models.ExcelFileTests)
The filename field should be generated based on the FileField filename
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/local/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/src/audit/test_models.py", line 177, in test_filename_generated
    excel_file = baker.make(ExcelFile, file=file)
  File "/usr/local/lib/python3.10/site-packages/model_bakery/baker.py", line 130, in make
    return baker.make(
  File "/usr/local/lib/python3.10/site-packages/model_bakery/baker.py", line 385, in make
    return self._make(**params)
  File "/usr/local/lib/python3.10/site-packages/model_bakery/baker.py", line 463, in _make
    instance = self.instance(
  File "/usr/local/lib/python3.10/site-packages/model_bakery/baker.py", line 497, in instance
    instance.save(**_save_kwargs)
  File "/src/audit/models.py", line 459, in save
    super(ExcelFile, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1819, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1743, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1744, in <listcomp>
    [
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1745, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1693, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/files.py", line 93, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/usr/local/lib/python3.10/site-packages/django/core/files/storage/base.py", line 38, in save
    name = self._save(name, content)
  File "/usr/local/lib/python3.10/site-packages/storages/backends/s3boto3.py", line 445, in _save
    obj.upload_fileobj(content, ExtraArgs=params, Config=self._transfer_config)
  File "/usr/local/lib/python3.10/site-packages/boto3/s3/inject.py", line 725, in object_upload_fileobj
    return self.meta.client.upload_fileobj(
  File "/usr/local/lib/python3.10/site-packages/boto3/s3/inject.py", line 636, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.10/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python3.10/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/s3transfer/upload.py", line 758, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The Access Key Id you provided does not exist in our records.


```

**Comment by jadudm** [comment]
closed via #1251
