### ISSUE TITLE
no such file Lines_in_progress.json

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1256]
```
======================================================================
ERROR: test_values_general (data_distro.tests.TestDataProcessing)
Look for sample expected values in general
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/suite.py", line 166, in _handleClassSetUp
    setUpClass()
  File "/src/data_distro/tests.py", line 57, in setUpClass
    TestDataProcessing.date_stamp1 = call_command(
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/newrelic/api/function_trace.py", line 154, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/src/data_distro/management/commands/public_data_loader.py", line 128, in handle
    timestamp = log_results(expected_objects_dict, kwargs)
  File "/src/data_distro/management/commands/handle_errors.py", line 114, in log_results
    errors = finish_error_files(date_stamp, options)
  File "/src/data_distro/management/commands/handle_errors.py", line 48, in finish_error_files
    if os.path.getsize(progress) == 0:
  File "/usr/local/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'data_distro/data_to_load/run_logs/Lines_in_progress.json'

```

**Comment by jadudm** [comment]
closed via #1251
